FPS: int = 60
FRAME_TIME: float = 1/FPS
GRID_CELL_SIZE: int = 16
HALF_GRID_CELL: int = 8
ROOM_SIZE_X: int = 10
ROOM_SIZE_Y: int = 7
DEBUG_DRAW_COLLIDERS: bool = False
GAME_RESTART_TIME: float = 0.9
GAME_DEATH_TIME: float = 0.7

PLAYER_DASH_TIME: float = 0.30
PLAYER_SPEED_NORMAL: float = 0.8
PLAYER_SPEED_DASH: float = 1.6
ENEMY_CHASE_DIST: float = GRID_CELL_SIZE*ROOM_SIZE_X/10*4  # 40% of a room


